# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc487534281698355db719088096bfdf1e5fc66e13fea7cd55fd4dc8cf5a10c9f1d8dcc904e2811a9a8eb715635c7d90e48768a6196ad526813c080acac0cbb2

test:
  secret_key_base: e0b627762e7cd9bbc4c16bd47f6d3cec36689980bacad87638d855058b2af034b349e6594c4a0e58b63669bf888f5094f011119dfc037ce5b1ae7375fa589ba8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
